FilaEncad fila;
    // ....
    // fila.enfileira(15);
    // fila.enfileira(85);
    // fila.enfileira(71);
    // fila.enfileira(75);
    // fila.enfileira(62);
    // fila.enfileira(70);
    // fila.enfileira(15);
    // fila.enfileira(15);